### ISSUE TITLE
Missing folders such as authorizer in receive_webhooks

### ISSUE THREAD

**Issue by linachenuiuc** [aws-samples/webhooks#2]
Hi there,

Thanks for providing examples for integrating aws services. 

In the Makefile, src/authorizer folder is specified. However, it didn't seem available in the repo. Will such missing folders to be added in future?

Thanks,
Lina

**Comment by wirjo** [comment]
Thanks @linachenuiuc - I will look into this cc @jplock

**Comment by jplock** [comment]
Good catch. The code isn’t missing, that’s a remnant from a previously unreleased implementation. We’ll get the Makefile fixed.

**Comment by linachenuiuc** [comment]
Great. Thanks.
